import path from 'node:path';import {fileURLToPath} from 'node:url';
import Evidence from '../models/Evidence.js';import ExtractedEntity from '../models/ExtractedEntity.js';import TimelineEvent from '../models/TimelineEvent.js';import Finding from '../models/Finding.js';import Incident from '../models/Incident.js';
import {OCRService} from './ocrService.js';import {AIExtractionService} from './aiExtractionService.js';import {detectMissing,detectConflicts,buildRelationships,buildReport,parseEventDate} from './processingLogic.js';import {asyncHandler,AppError} from '../utils/errors.js';
const stages=['EXTRACTING','TIMELINE_BUILDING','CHECKING_MISSING','CHECKING_CONFLICTS','REDACTING','GENERATING_REPORT','COMPLETED'];
const uploadsDir=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../uploads');
export class IncidentProcessingService{
 constructor({ocr=new OCRService(),ai=new AIExtractionService()}={}){this.ocr=ocr;this.ai=ai;}
 async process(incident,user){
  await Promise.all([ExtractedEntity.deleteMany({incident:incident._id}),TimelineEvent.deleteMany({incident:incident._id}),Finding.deleteMany({incident:incident._id})]);
  const evidence=await Evidence.find({incident:incident._id}).select('+extractedText').sort({uploadedAt:1});if(!evidence.length)throw new AppError(400,'Add evidence before processing.');
  const items=[];incident.status='PROCESSING';
  try{
   incident.processingStatus=stages[0];await incident.save();
   for(const doc of evidence){doc.status='PROCESSING';await doc.save();const text=doc.extractedText||await this.ocr.extractText({originalName:doc.originalName,filePath:path.join(uploadsDir,doc.storedName)});doc.extractedText=text;
    const parsed=await this.ai.extractInformation(text,doc.evidenceCode);const entities=parsed.entities.map(e=>({...e,incident:incident._id,evidence:doc._id}));items.push({id:doc.evidenceCode,doc,text,entities:parsed.entities,eventType:parsed.eventType,sha256:doc.sha256});
    await ExtractedEntity.insertMany(entities);doc.status='PROCESSED';doc.processingMethod=process.env.AI_API_KEY?'LLM+OCR adapter':'DEMO_RULES';await doc.save();}
   incident.processingStatus=stages[1];await incident.save();
   const events=items.map((item,i)=>{const time=item.entities.find(e=>e.type==='TIME')?.value||null;return {incident:incident._id,evidence:item.doc._id,eventId:`EV-${item.id}`,eventTime:parseEventDate(time),eventTimeText:time,eventType:item.eventType,description:item.entities.find(e=>e.type==='AMOUNT')?`${item.eventType.replaceAll('_',' ').toLowerCase()} — ${item.entities.find(e=>e.type==='AMOUNT').value}`:item.eventType.replaceAll('_',' ').toLowerCase(),confidence:item.entities.length?Math.max(...item.entities.map(e=>e.confidence)):.5,sourceEvidenceId:item.id};}).sort((a,b)=>(a.eventTime?.getTime()??Infinity)-(b.eventTime?.getTime()??Infinity));
   const savedEvents=await TimelineEvent.insertMany(events);incident.processingStatus=stages[2];await incident.save();
   const gaps=detectMissing(items);if(gaps.length)await Finding.insertMany(gaps.map(g=>({incident:incident._id,kind:'MISSING',type:g.field,description:g.suggestion,evidenceIds:[evidence.find(e=>e.evidenceCode===g.evidenceId)._id],metadata:g})));
   incident.processingStatus=stages[3];await incident.save();const conflictList=detectConflicts(items);if(conflictList.length)await Finding.insertMany(conflictList.map(c=>({incident:incident._id,kind:'CONFLICT',type:c.type,severity:c.severity,description:c.description,evidenceIds:c.evidenceIds.map(id=>evidence.find(e=>e.evidenceCode===id)._id)})));
   incident.processingStatus=stages[4];await incident.save();const pii=items.flatMap(item=>item.entities.filter(e=>['PHONE','EMAIL','ACCOUNT_NUMBER','UPI_ID','ADDRESS','GOVERNMENT_ID'].includes(e.type)).map(e=>({incident:incident._id,kind:'PII',type:e.type,description:'Sensitive value detected; protected derivative available.',evidenceIds:[item.doc._id],metadata:{entityId:e.entityId}})));if(pii.length)await Finding.insertMany(pii);
   const relationships=buildRelationships(items,savedEvents);if(relationships.length)await Finding.insertMany(relationships.map(r=>({incident:incident._id,kind:'RELATIONSHIP',type:r.relationshipType,description:`${r.sourceType} ${r.relationshipType} ${r.targetType}`,evidenceIds:r.sourceEvidenceIds.map(id=>evidence.find(e=>e.evidenceCode===id)._id),metadata:r,relationshipType:r.relationshipType,sourceType:r.sourceType,targetType:r.targetType,sourceId:r.sourceId,targetId:r.targetId})));
   incident.processingStatus=stages[5];await incident.save();const entityDocs=await ExtractedEntity.find({incident:incident._id});const persistedEvents=await TimelineEvent.find({incident:incident._id}).sort({eventTime:1});const findingDocs=await Finding.find({incident:incident._id});const miss=findingDocs.filter(x=>x.kind==='MISSING').map(x=>({evidenceId:evidence.find(e=>e._id.equals(x.evidenceIds[0]))?.evidenceCode,field:x.type,suggestion:x.description}));const conflicts=findingDocs.filter(x=>x.kind==='CONFLICT').map(x=>({type:x.type,severity:x.severity,description:x.description,evidenceIds:x.evidenceIds.map(id=>evidence.find(e=>e._id.equals(id))?.evidenceCode)}));
   incident.report=buildReport({incident,evidence,events:persistedEvents,missing:miss,conflicts,entities:entityDocs,relationships:relationships.map(r=>({...r})),generatedBy:user.name});incident.status='UNDER_REVIEW';incident.processingStatus=stages[6];incident.processedAt=new Date();await incident.save();return incident;
  }catch(err){incident.status='FAILED';incident.processingStatus='FAILED';await incident.save();await Evidence.updateMany({incident:incident._id,status:'PROCESSING'},{$set:{status:'FAILED'}});throw err;}
 }
}
export const processIncident=asyncHandler(async(req,res)=>{if(req.incident.status==='PROCESSING')throw new AppError(409,'Evidence processing is already running.');req.incident.status='PROCESSING';req.incident.processingStatus='EXTRACTING';await req.incident.save();const incident=req.incident,user=req.user;res.status(202).json({incidentId:incident._id,processingStatus:incident.processingStatus});setImmediate(()=>new IncidentProcessingService().process(incident,user).catch(err=>console.error(`Incident processing failed: ${err.message}`)));});
